# Netlify Configuration File for Security Headers (Grade 'A' Fix)

[[headers]]
  for = "/*"

  [headers.values]
    
    # Content-Security-Policy (CSP) - XSS protection
    Content-Security-Policy = "default-src 'self' https://cdn.jsdelivr.net https://fonts.gstatic.com; script-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; style-src 'self' https://fonts.googleapis.com 'unsafe-inline'; font-src 'self' data: https://fonts.gstatic.com"

    # Clickjacking and MIME Sniffing protection
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

    # Referrer and Permissions Policy
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

    # Enforce HTTPS
    Strict-Transport-Security = "max-age=63072000; includeSubDomains"